kind: Pod
apiVersion: v1
metadata:
  name: pod02
spec:
  containers:
    - name: centos
      image: centos:7
      command:
        - "sleep"
        - "1000"
## Number in Kubernetes should be quoted
