---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-database
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
---
